### ISSUE TITLE
Bad uint conversion on `getutxout`

### ISSUE THREAD

**Issue by darosior** [lvaccaro/esplora_clnd_plugin#10]
I started having failures with the esplora backend on Lamp, and tracking it down this https://github.com/lvaccaro/esplora_clnd_plugin/blob/0310dfddf429efee1c13826e281b1522c7f2f777/esplora.c#L336-L339
seems wrong to me: what if the `vout` is `0` ?

**Comment by lvaccaro** [comment]
Nice catch! 

> On success, the function returns the converted integral number as an unsigned long int value.
> If no valid conversion could be performed, a zero value is returned.
from https://www.cplusplus.com/reference/cstdlib/strtoul/

Could we add a `strcmp` to avoid the zero vout condition?

**Comment by darosior** [comment]
I have a patch which adds a proper string->u32 conversion helper.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
