### ISSUE TITLE
Update to v0.9.1

### ISSUE THREAD

**Issue by lvaccaro** [lvaccaro/esplora_clnd_plugin#17]
Commit https://github.com/ElementsProject/lightning/commit/3ed03f9c8f6712a7939bb6d2d2cd1a5fbe1b4df8 updates prototype of `json_parse_input `, mostly used in esplora. This requires to be updates in order to make it working on v0.9.1

**Comment by vincenzopalazzo** [comment]
It can be close by https://github.com/lvaccaro/esplora_clnd_plugin/pull/33?

**Comment by lvaccaro** [comment]
right
